[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_avatars = "56kfTdE1xmCkZ2eDuikD7S5Mr15nmdzQENDWfmdMVtt"

[programs.devnet]
solana_avatars = "56kfTdE1xmCkZ2eDuikD7S5Mr15nmdzQENDWfmdMVtt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" # localnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
